import Header from "../../Header/Header";
import type { Metadata } from "next";
import Footer from "@/app/components/Footer/Footer";
import "../../../../../sass/global.scss";
import Provide from "../../../rtk/provider";

export const metadata: Metadata = {
  title: "MiniShop",
  description: "Generated by create next app",
};

export default function LayoutMainPage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
