import Header from "./components/Header/Header";
import type { Metadata } from "next";
import Footer from "./components/Footer/Footer";
import "./globals.css";
import "../../sass/global.scss";
import Provide from "./rtk/provider";

export const metadata: Metadata = {
  title: "MiniShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provide>
          <Header />
          {children}
          <Footer />
        </Provide>
      </body>
    </html>
  );
}
